# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xisjMa4tKuqNGxg2abXcSVWCLN-8qqCg
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.rc('font', family='AppleGothic')
plt.rcParams['figure.figsize'] = (10,5)

jeju_df=pd.upload.csv('data.csv')
jeju_df.head()

from google.colab import files
uploaded = files.upload()

import io
jeju_df = pd.read_csv(io.BytesIO(uploaded['jeju_card.csv']))  # Change the key to 'jeju_card.csv'

jeju_df.head()

groupby_ym = jeju_df.groupby('연월').sum(numeric_only=True).reset_index()
groupby_ym

sns.barplot(data=groupby_ym, x='연월', y='이용금액')
plt.xticks(rotation=90)
plt.title('연월별 카드 이용 금액')
plt.gca().yaxis.set_major_formatter(plt.FuncFormatter(lambda x,_: f'{x/100000000:,.0f}'))
plt.ylabel('이용금액(억)')

groupby_age_ym=jeju_df.groupby(['연령대','연월']).sum(numeric_only=True).reset_index()
groupby_age_ym